apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: spark-2959
  share: /nfs/shared
reclaimPolicy: Retain
mountOptions:
  - nfsvers=4.2