apiVersion: v1
kind: Pod
metadata:
  name: rdma-bw-server
  labels:
    app: rdma-bw
    role: server
spec:
  nodeSelector:
    kubernetes.io/hostname: "spark-ba63"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
    - name: srv
      image: nvidia/cuda:12.6.2-runtime-ubuntu24.04
      securityContext: { runAsUser: 0 }
      command: ["/bin/bash","/run.sh"]
      volumeMounts:
        - name: script
          mountPath: /run.sh
          subPath: run.sh
      resources:
        limits:
          rdma/rdma_shared_device_a: 63
        requests:
          rdma/rdma_shared_device_a: 63
  volumes:
    - name: script
      configMap:
        name: rdma-bw-scripts
---
apiVersion: v1
kind: Pod
metadata:
  name: rdma-bw-client
  labels:
    app: rdma-bw
    role: client
spec:
  nodeSelector:
    kubernetes.io/hostname: "spark-2959"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
    - name: cli
      image: nvidia/cuda:12.6.2-runtime-ubuntu24.04
      securityContext: { runAsUser: 0 }
      command: ["/bin/bash","/run.sh"]
      env:
        - name: SERVER_IP
          value: rdma-bw-server
        - name: INSTALL_DEPS
          value: "1"
      volumeMounts:
        - name: script
          mountPath: /run.sh
          subPath: run.sh
      resources:
        limits:
          rdma/rdma_shared_device_a: 63
        requests:
          rdma/rdma_shared_device_a: 63
  volumes:
    - name: script
      configMap:
        name: rdma-bw-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: rdma-bw-server
spec:
  clusterIP: None
  selector:
    app: rdma-bw
    role: server
  ports:
    - name: rdma
      port: 18515
      targetPort: 18515
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-bw-scripts
data:
  run.sh: |
    #!/bin/bash
    set -e
    if [ "${INSTALL_DEPS:-1}" = "1" ]; then
      trap 'if [ -f /tmp/resolv.conf.bak ]; then cat /tmp/resolv.conf.bak > /etc/resolv.conf; rm -f /tmp/resolv.conf.bak; fi' EXIT
      cp /etc/resolv.conf /tmp/resolv.conf.bak
      printf 'nameserver 8.8.8.8\nnameserver 1.1.1.1\n' > /etc/resolv.conf
      for attempt in $(seq 1 3); do
        if apt-get -o Acquire::ForceIPv4=true update; then
          break
        fi
        echo "[apt] update attempt ${attempt} failed; retrying in 5s..."
        sleep 5
      done
      for attempt in $(seq 1 3); do
        if DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::ForceIPv4=true install -y --no-install-recommends rdma-core perftest ca-certificates iproute2; then
          break
        fi
        echo "[apt] install attempt ${attempt} failed; retrying in 5s..."
        sleep 5
      done
      cat /tmp/resolv.conf.bak > /etc/resolv.conf
      rm -f /tmp/resolv.conf.bak
      trap - EXIT
    fi
    if ! command -v ib_write_bw >/dev/null 2>&1; then
      echo "[error] ib_write_bw not found in PATH; ensure the image contains perftest or set INSTALL_DEPS=1 with network access" >&2
      exit 2
    fi
    IB_DEVICE="${IB_DEVICE:-}"
    if [ -z "$IB_DEVICE" ]; then
      echo "[info] detecting RDMA devices available to the pod..."
      if command -v ibv_devices >/dev/null 2>&1; then
        IB_DEVICE=$(ibv_devices | awk 'NR>2 {print $1}' | head -n1 || true)
      fi
    fi
    if [ -z "$IB_DEVICE" ] && command -v ibv_devinfo >/dev/null 2>&1; then
      IB_DEVICE=$(ibv_devinfo -l | awk '{print $1}' | head -n1 || true)
    fi
    if [ -z "$IB_DEVICE" ] && [ -d /sys/class/infiniband ]; then
      IB_DEVICE=$(ls /sys/class/infiniband | head -n1 || true)
    fi
    if [ -z "$IB_DEVICE" ]; then
      echo "[error] no RDMA devices found (ibv tools not available or no devices exposed)" >&2
      command -v ibv_devices >/dev/null 2>&1 && ibv_devices || true
      ls -l /sys/class/infiniband || true
      exit 3
    fi
    echo "[info] using IB device: $IB_DEVICE"
    if command -v rdma >/dev/null 2>&1; then
      rdma link show || true
    fi
    ls -l /sys/class/infiniband/"$IB_DEVICE" || true
    if [ -z "$SERVER_IP" ]; then
      echo "[server] starting ib_write_bw on port 18515"; exec ib_write_bw -d "$IB_DEVICE" -F -s 65536 -n 1000 -x 0 -p 18515
    else
      TARGET_IP="$SERVER_IP"
      if [[ ! "$TARGET_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "[client] waiting for $TARGET_IP to resolve..."
        for attempt in $(seq 1 30); do
          RESOLVED_IP=$(getent hosts "$TARGET_IP" | awk '{print $1}' | head -n1 || true)
          if [ -n "$RESOLVED_IP" ]; then
            TARGET_IP="$RESOLVED_IP"
            break
          fi
          echo "[client] attempt ${attempt}/30: still resolving $TARGET_IP"
          sleep 2
        done
        if [[ ! "$TARGET_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "[client] failed to resolve $SERVER_IP after waiting" >&2
          exit 1
        fi
      fi
      echo "[client] connecting to $TARGET_IP"; sleep 3
      SUCCESS=0
      for attempt in $(seq 1 5); do
        if ib_write_bw -d "$IB_DEVICE" -F -s 65536 -n 1000 -x 0 -p 18515 "$TARGET_IP" --report_gbits; then
          SUCCESS=1
          break
        fi
        echo "[client] attempt ${attempt}/5 failed to connect; retrying in 5s..."
        sleep 5
      done
      if [ "$SUCCESS" -ne 1 ]; then
        echo "[client] giving up after 5 failed attempts to reach $TARGET_IP" >&2
        exit 4
      fi
    fi
